azerothcore/acore-cms

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/user/user.php
fix + code style improvements by php-cs-fixer
> fix(update-password): make case unsensitive the username comparison uring the password update

- data/docker/Wordpress.Dockerfile
- srv/wordpress/wp-content/plugins/acore-wp-plugin/vendor/acore-php/acore-php/account/src/Entity/AccountEntity.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/vendor/acore-php/acore-php/account/src/Repository/AccountRepository.php
Thanks @MasterKing32, @r0m1ntik
> feat(auth-system): update the verifyAccount function adding salt and SRP6 algorithm

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/AdminPanel/Settings.view.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/ServerInfo/SInfoApi.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/vendor/acore-php/acore-php/soap/src/Services/SoapMgr.php
This PR closes #24.
Allow to check SOAP credentials at the bottom of the Settings view.
> Add Check SOAP button in AC settings.

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/containers/ACoreServices.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/char_change.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/char_transfer.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/item_send.php
This PR close #25.
What was done is centralize the code of getCharName into the main character entity repository.
> Refactor getCharName

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/AdminPanel/AdminPanel.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/AdminPanel/Settings.controller.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/AdminPanel/Settings.view.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/web/assets/admin_logo.svg
New feature Give PvP Rewards (close #40).
**What you can configure?**
- Set amount of myCred points to give
- Set who will get the rewards (Winners or Loosers)
- Set the bracket who will be rewarded (specify one or give to all)
- Month and Year to calculate the total amount.
- Allow to give an extra reward to Top players (5, 10, 15, 20 or 25).
2 options, a Preview to view a total of 10 values and Send Rewards to give all points.
**Limitations:**
- Auth and Character database should be in the same server.
**Impact**
- None.
> Feature PvP Rewards

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/core/app.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/woocommerce.php
This are minor fixes for issues #42 and #43, but need testing specific for the woocommerce part.
> Fix issues #42 and #43

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/CharactersMenu/CharactersMenu.php
This PR fix #53.
- With an account that has subscriber role check if can see Characters view and use the order feature.
- With any other role, check if can see Characters view and use the order feature.
> Fix capability issue in Characters view

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/UserPanel/User.controller.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/UserPanel/User.view.php
Fix details found in RAF module.
> Fix RAF module

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/CharactersMenu/Characters.controller.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/char_change.php
Add a validation to avoid #41 error and fix function call when ordering characters caused by raf pr.
> Fix char errors

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/UserPanel/User.controller.php
possible fix for https://github.com/azerothcore/acore-cms/issues/59
> fix: prevent user to recruit himself, closes #59

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/AdminPanel/AdminPanel.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/AdminPanel/Settings.view.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/UserPanel/User.controller.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/UserPanel/User.view.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/containers/ACoreServices.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/services/Opts.php
This PR add a lot of graphic improves, proposing the following changes:
- adding bootstrap to wp-admin (CHECK A FEW VIEWS).
- add bootstrap components to some settings views.
- improves in RAF messages and minor UI bugs
- also add a new feature to add an optional simple IP check that validates the site user IP and account last ip with the last ip of the recruiter.
This PR close #59.
> RAF Fix and improves

- srv/wordpress/wp-content/plugins/acore-wp-plugin/acore-wp-plugin.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/AdminPanel/AdminPanel.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/AdminPanel/Settings.view.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/CharactersMenu/Characters.controller.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/CharactersMenu/Characters.view.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/CharactersMenu/CharactersMenu.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/ServerInfo/SInfoApi.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/UserPanel/User.view.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/UserPanel/UserMenu.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/web/assets/css/main.css
This PR includes a style rework of the plugin admin views, implementing [Bootstrap 5](https://getbootstrap.com/) on the views.
Changes proposed:
- Implement column grid system in all views.
- Change default wordpress box for boostrap card.
- Replace many wordpress tables for bootstrap tables
- Add ACORE_SLUG as a prefix for all acore plugin menu pages.
Test to do:
- Just go arround the pages and see that all is in order.
> Style improves

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/AdminPanel/Settings.controller.php
This PR create myCred logs when giving pvp rewards, usign a custom tag called 'pvp-rewards' as Reference and month + year as Entry.
Test to do:
- Use PVP rewards and give it for any month and year, process should finish without trouble and be able to see them in Log view.
- If the executer of the process receive rewards, should can be able to see the detail in the personal myCred history.
> Add pvp-rewards logs

- srv/wordpress/.htaccess
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/UserPanel/User.view.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/components/UserPanel/UserMenu.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/containers/ACoreServices.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/user/user.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/carbon_copy.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/char_change.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/char_transfer.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/item_send.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/services/UserService.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/vendor/acore-php/acore-php/defines/src/Conf.php
This PR add many minor improvements.
Changes proposed:
- Fix an issue with email validation when change email (probably fix #7).
- Hide many system messages to users without manage_options and update_core permissions.
- Add a custom widget showing some player info.
- Add a new copyright footer.
- Remove warning for woocommerce (close #19 )
- Improve password generator based on #17
> Add UI and function improvements

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/carbon_copy.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/cart_validation.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/char_change.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/char_transfer.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/item_send.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/woocommerce.php
This will fix the issue when a player try to add a product or service to the cart from the catalogue instead of the product view.
This should close #41
> [Fix] Add more priority for add to cart validation functions

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/char_change.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/item_send.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/vendor/acore-php/acore-php/character/src/Services/CharacterSoapMgr.php
closes https://github.com/azerothcore/acore-cms/issues/67
fix also the item_send service when the user send an item to a specific character
> fix: restore characters service

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/services/UserService.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/vendor/acore-php/acore-php/defines/src/Conf.php
> Fix password validation #69

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Components/AdminPanel/SettingsView.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/User/User.php
Fix notice errors introduced in #85 and fix an error that happens when a not existing cms user try to connect and there is no connection to acore auth db.
> [Fix] Add minor fixes related to pvp rewards view

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Components/UserPanel/Pages/RafProgressPage.php
This PR removes exposure of the username in the RAF view (see [chromiecraft/chromiecraft#3082](https://github.com/chromiecraft/chromiecraft/issues/3082))
> Hide username from raf view

- docs/configure-cms.md
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/CartValidation.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/GuildChange.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/WooCommerce.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Manager/ACoreServices.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Manager/Soap/GuildService.php
> feat: Guild Rename service

- docs/configure-cms.md
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Components/Tools/ToolsApi.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/CartValidation.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/FieldElements.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/ItemRestoration.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/ItemSend.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/WooCommerce.php
co-author: @Eronox
closes https://github.com/azerothcore/acore-cms/issues/27
How to test:
- change worldserver.conf of item delete
- `ItemDelete.Method = 1`
- `ItemDelete.Quality = 0`
- `ItemDelete.ItemLevel = 1`
Known issue: we can't use this service with the worldserver conf `ItemDelete.Vendor = 1`
> feat: Item restoration restoration

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/FieldElements.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/ItemRestoration.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Manager/Character/Entity/CharacterEntity.php
Issue: https://github.com/azerothcore/acore-cms/issues/96
No CSS has been implemented since I wasn't sure if it was needed for this
https://user-images.githubusercontent.com/20383130/160244618-689d0ec4-40b9-4b4e-be25-0da065524fc0.mp4
> feat: show character icons on shop services

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/ItemRestoration.php
Closes: https://github.com/azerothcore/acore-cms/issues/109
> Feat: add loading spinner icon to item restoration

- docs/configure-cms.md
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Components/AdminPanel/Pages/Tools.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/CartValidation.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/NameUnlock.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/WooCommerce.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Manager/ACoreServices.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Manager/Auth/Entity/AccountBannedEntity.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Manager/Auth/Entity/AccountEntity.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Manager/Character/Entity/CharacterEntity.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Manager/Opts.php
closes https://github.com/azerothcore/acore-cms/issues/114
> feat: name unlock service

- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Components/AdminPanel/Pages/Tools.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Components/AdminPanel/SettingsController.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/NameUnlock.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Manager/Opts.php
* You can now select a character from your account which will receive the unlocked name immediately
* Added a db table to allow unlocking banned names
> feat: add target character to name unlock

- docs/configure-cms.md
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/CartValidation.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/ItemRestoration.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/TransmogItemSend.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/TransmogItemsetSend.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/WooCommerce.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Manager/ACoreServices.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Manager/Soap/TransmogService.php
This PR is ready but unfortunately the current mod-transmog version can't work with this because the console is not enabled to execute the transmog commands and enabling these commands for the console it is possible to execute the commands only when the player is online.
Hope to open a PR to mod-transmog soon to improve this.
acore-cms side should be ok at least ✅ 
closes https://github.com/azerothcore/acore-cms/issues/107
> feat: add transmog item send service

- docs/README.md
Fix docker-compose installation error
> fix (README.md): Typing error

- data/docker/Wordpress.Dockerfile
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Components/UnstuckMenu/UnstuckApi.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Components/UserPanel/UserMenu.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/User/User.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/CharChange.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/CharTransfer.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/GuildChange.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/ItemRestoration.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/ItemSend.php
- srv/wordpress/wp-content/plugins/acore-wp-plugin/src/Hooks/WooCommerce/TransmogItemSend.php
Co-authored by: Yehonal yehonal.azeroth@gmail.com
> chore: update acore-wp-plugin
